# Generated by Django 5.2.8 on 2025-11-07 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPlan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text="Código interno (ej: 'esencial', 'pro', 'planificador')", max_length=30, unique=True)),
                ('nombre', models.CharField(help_text="Nombre comercial del plan (ej: 'Plan Profesional')", max_length=100)),
                ('precio_base_mensual', models.DecimalField(decimal_places=2, default=0, help_text="Precio mensual del paquete (si es 0, es 'Planificador')", max_digits=10)),
                ('max_condominios', models.PositiveSmallIntegerField(default=1, help_text='Número máximo de condominios permitidos en este plan')),
                ('max_unidades', models.PositiveSmallIntegerField(default=100, help_text='Número máximo de unidades (deptos/casas) totales')),
                ('features_json', models.JSONField(default=dict, help_text='Banderas JSON que definen qué módulos incluye este plan')),
                ('es_personalizable', models.BooleanField(default=False, help_text="Si es True, este plan es el 'Planificador' (cotizable)")),
            ],
            options={
                'verbose_name': 'Catálogo: Plan de Suscripción',
                'verbose_name_plural': 'Catálogo: Planes de Suscripción',
                'db_table': 'cat_plan',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('prueba', 'En Prueba'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='prueba', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_termino', models.DateField(blank=True, help_text='Fecha de fin (para planes de prueba o si se cancela)', null=True)),
                ('monto_mensual_final', models.DecimalField(decimal_places=2, help_text='El monto final calculado que el cliente paga por mes', max_digits=10)),
                ('max_condominios', models.PositiveSmallIntegerField(default=1, help_text='Límite real de condominios para ESTA suscripción')),
                ('max_unidades', models.PositiveSmallIntegerField(default=100, help_text='Límite real de unidades para ESTA suscripción')),
                ('features_json', models.JSONField(default=dict, help_text='Banderas JSON que definen los módulos de ESTA suscripción')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('id_plan', models.ForeignKey(db_column='id_plan', help_text='El plan base o plantilla seleccionado', on_delete=django.db.models.deletion.PROTECT, to='core.catplan')),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', help_text='El usuario (administrador) dueño de esta suscripción', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción de Usuario',
                'verbose_name_plural': 'Suscripciones de Usuario',
                'db_table': 'suscripcion',
            },
        ),
    ]
