# Generated by Django 5.2.8 on 2025-11-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_gastocategoria_gasto"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatConceptoCargo",
            fields=[
                (
                    "id_concepto_cargo",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                "verbose_name": "Catálogo: Concepto de Cargo",
                "verbose_name_plural": "Catálogo: Conceptos de Cargos",
                "db_table": "cat_concepto_cargo",
            },
        ),
        migrations.CreateModel(
            name="ProrrateoRegla",
            fields=[
                ("id_prorrateo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ordinario", "Ordinario"),
                            ("extra", "Extraordinario"),
                            ("especial", "Especial"),
                        ],
                        default="ordinario",
                        max_length=20,
                    ),
                ),
                (
                    "criterio",
                    models.CharField(
                        choices=[
                            ("coef_prop", "Coeficiente de Propiedad"),
                            ("por_m2", "Por Metros Cuadrados"),
                            ("igualitario", "Igualitario"),
                            ("por_tipo", "Por Tipo de Unidad"),
                            ("monto_fijo", "Monto Fijo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "peso_vivienda",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "peso_bodega",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "peso_estacionamiento",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "id_concepto_cargo",
                    models.ForeignKey(
                        db_column="id_concepto_cargo",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.catconceptocargo",
                    ),
                ),
                (
                    "id_condominio",
                    models.ForeignKey(
                        db_column="id_condominio",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.condominio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Prorrateo",
                "verbose_name_plural": "Reglas de Prorrateo",
                "db_table": "prorrateo_regla",
                "unique_together": {
                    ("id_condominio", "id_concepto_cargo", "vigente_desde", "tipo")
                },
            },
        ),
        migrations.CreateModel(
            name="ProrrateoFactorUnidad",
            fields=[
                ("id_factor", models.AutoField(primary_key=True, serialize=False)),
                ("factor", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "id_unidad",
                    models.ForeignKey(
                        db_column="id_unidad",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.unidad",
                    ),
                ),
                (
                    "id_prorrateo",
                    models.ForeignKey(
                        db_column="id_prorrateo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.prorrateoregla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factor de Prorrateo por Unidad",
                "verbose_name_plural": "Factores de Prorrateo por Unidad",
                "db_table": "prorrateo_factor_unidad",
                "unique_together": {("id_prorrateo", "id_unidad")},
            },
        ),
    ]
