# Generated by Django 5.2.8 on 2025-11-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_catconceptocargo_prorrateoregla_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatCobroEstado",
            fields=[
                (
                    "id_cobro_estado",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Catálogo: Estado de Cobro",
                "verbose_name_plural": "Catálogo: Estados de Cobro",
                "db_table": "cat_cobro_estado",
            },
        ),
        migrations.CreateModel(
            name="CargoIndividual",
            fields=[
                ("id_cargo_indv", models.AutoField(primary_key=True, serialize=False)),
                ("periodo", models.CharField(max_length=6)),
                ("tipo", models.CharField(max_length=30)),
                ("referencia", models.CharField(blank=True, max_length=60, null=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("detalle", models.CharField(blank=True, max_length=300, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_unidad",
                    models.ForeignKey(
                        db_column="id_unidad",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.unidad",
                    ),
                ),
            ],
            options={
                "db_table": "cargo_individual",
            },
        ),
        migrations.CreateModel(
            name="CargoUnidad",
            fields=[
                ("id_cargo_uni", models.AutoField(primary_key=True, serialize=False)),
                ("periodo", models.CharField(max_length=6)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("extra", "Extra"),
                            ("ajuste", "Ajuste"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("detalle", models.CharField(blank=True, max_length=300, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_concepto_cargo",
                    models.ForeignKey(
                        db_column="id_concepto_cargo",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.catconceptocargo",
                    ),
                ),
                (
                    "id_unidad",
                    models.ForeignKey(
                        db_column="id_unidad",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.unidad",
                    ),
                ),
            ],
            options={
                "db_table": "cargo_unidad",
            },
        ),
        migrations.CreateModel(
            name="Cobro",
            fields=[
                ("id_cobro", models.AutoField(primary_key=True, serialize=False)),
                ("periodo", models.CharField(max_length=6)),
                ("emitido_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensual", "Mensual"),
                            ("extraordinario", "Extraordinario"),
                            ("manual", "Manual"),
                        ],
                        default="mensual",
                        max_length=20,
                    ),
                ),
                (
                    "total_cargos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_descuentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_interes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "id_cobro_estado",
                    models.ForeignKey(
                        db_column="id_cobro_estado",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.catcobroestado",
                    ),
                ),
                (
                    "id_prorrateo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_prorrateo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.prorrateoregla",
                    ),
                ),
                (
                    "id_unidad",
                    models.ForeignKey(
                        db_column="id_unidad",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.unidad",
                    ),
                ),
            ],
            options={
                "db_table": "cobro",
            },
        ),
        migrations.CreateModel(
            name="CobroDetalle",
            fields=[
                ("id_cobro_det", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cargo_comun", "Gasto Común (Prorrateo)"),
                            ("cargo_individual", "Cargo Individual"),
                            ("interes_mora", "Interés por Mora"),
                            ("descuento", "Descuento"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("glosa", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "id_cargo_indv",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cargo_indv",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.cargoindividual",
                    ),
                ),
                (
                    "id_cargo_uni",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_cargo_uni",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.cargounidad",
                    ),
                ),
                (
                    "id_cobro",
                    models.ForeignKey(
                        db_column="id_cobro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cobro",
                    ),
                ),
            ],
            options={
                "db_table": "cobro_detalle",
            },
        ),
        migrations.AddIndex(
            model_name="cargounidad",
            index=models.Index(
                fields=["periodo", "id_unidad"], name="ix_cargo_periodo_unidad"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cobro",
            unique_together={("id_unidad", "periodo", "tipo")},
        ),
    ]
