# Generated by Django 5.2.8 on 2025-11-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_catcobroestado_cargoindividual_cargounidad_cobro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatEstadoTx",
            fields=[
                ("id_estado_tx", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name": "Catálogo: Estado Transacción",
                "verbose_name_plural": "Catálogo: Estados Transacción",
                "db_table": "cat_estado_tx",
            },
        ),
        migrations.CreateModel(
            name="CatMetodoPago",
            fields=[
                ("id_metodo_pago", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "Catálogo: Método de Pago",
                "verbose_name_plural": "Catálogo: Métodos de Pago",
                "db_table": "cat_metodo_pago",
            },
        ),
        migrations.CreateModel(
            name="CatPasarela",
            fields=[
                ("id_pasarela", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name": "Catálogo: Pasarela de Pago",
                "verbose_name_plural": "Catálogo: Pasarelas de Pago",
                "db_table": "cat_pasarela",
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_pago", models.DateTimeField()),
                ("periodo", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("anticipo", "Anticipo"),
                            ("ajuste", "Ajuste"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "ref_externa",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "id_metodo_pago",
                    models.ForeignKey(
                        db_column="id_metodo_pago",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.catmetodopago",
                    ),
                ),
                (
                    "id_unidad",
                    models.ForeignKey(
                        db_column="id_unidad",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.unidad",
                    ),
                ),
            ],
            options={
                "db_table": "pago",
            },
        ),
        migrations.CreateModel(
            name="ComprobantePago",
            fields=[
                ("id_compr_pago", models.AutoField(primary_key=True, serialize=False)),
                ("folio", models.CharField(max_length=40, unique=True)),
                ("url_pdf", models.CharField(blank=True, max_length=500, null=True)),
                ("emitido_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_pago",
                    models.OneToOneField(
                        db_column="id_pago",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pago",
                    ),
                ),
            ],
            options={
                "db_table": "comprobante_pago",
            },
        ),
        migrations.CreateModel(
            name="PagoAplicacion",
            fields=[
                ("id_pago_aplic", models.AutoField(primary_key=True, serialize=False)),
                (
                    "monto_aplicado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("aplicado_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_cobro",
                    models.ForeignKey(
                        db_column="id_cobro",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cobro",
                    ),
                ),
                (
                    "id_pago",
                    models.ForeignKey(
                        db_column="id_pago",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pago",
                    ),
                ),
            ],
            options={
                "db_table": "pago_aplicacion",
            },
        ),
        migrations.CreateModel(
            name="PasarelaTx",
            fields=[
                ("id_pasarela_tx", models.AutoField(primary_key=True, serialize=False)),
                ("payload_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id_estado_tx",
                    models.ForeignKey(
                        db_column="id_estado_tx",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.catestadotx",
                    ),
                ),
                (
                    "id_pago",
                    models.ForeignKey(
                        db_column="id_pago",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pago",
                    ),
                ),
                (
                    "id_pasarela",
                    models.ForeignKey(
                        db_column="id_pasarela",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.catpasarela",
                    ),
                ),
            ],
            options={
                "db_table": "pasarela_tx",
            },
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["id_unidad", "periodo"], name="ix_pago_unidad_periodo"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["id_unidad", "fecha_pago"], name="ix_pago_unidad_fecha"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pagoaplicacion",
            unique_together={("id_pago", "id_cobro")},
        ),
    ]
