# Generated by Django 5.2.8 on 2025-11-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_catestadotx_catmetodopago_catpasarela_pago_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                ("id_trabajador", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=40)),
                ("rut_base", models.IntegerField()),
                ("rut_dv", models.CharField(max_length=1)),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("cargo", models.CharField(max_length=80)),
                ("email", models.EmailField(blank=True, max_length=120, null=True)),
                ("telefono", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "id_condominio",
                    models.ForeignKey(
                        db_column="id_condominio",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.condominio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
                "db_table": "trabajador",
                "unique_together": {("id_condominio", "rut_base", "rut_dv")},
            },
        ),
        migrations.CreateModel(
            name="TrabajadorContrato",
            fields=[
                ("id_contrato", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_contrato", models.CharField(max_length=40)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField(blank=True, null=True)),
                (
                    "sueldo_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("jornada", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "documento_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "id_trabajador",
                    models.ForeignKey(
                        db_column="id_trabajador",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de Trabajador",
                "verbose_name_plural": "Contratos de Trabajadores",
                "db_table": "trabajador_contrato",
            },
        ),
        migrations.CreateModel(
            name="Remuneracion",
            fields=[
                (
                    "id_remuneracion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensual", "Mensual"),
                            ("finiquito", "Finiquito"),
                            ("bono", "Bono"),
                            ("retroactivo", "Retroactivo"),
                            ("otro", "Otro"),
                        ],
                        default="mensual",
                        max_length=20,
                    ),
                ),
                ("periodo", models.CharField(max_length=6)),
                (
                    "bruto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "imposiciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("liquido", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "comprobante_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "id_metodo_pago",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_metodo_pago",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.catmetodopago",
                    ),
                ),
                (
                    "id_trabajador",
                    models.ForeignKey(
                        db_column="id_trabajador",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remuneración",
                "verbose_name_plural": "Remuneraciones",
                "db_table": "remuneracion",
                "unique_together": {("id_trabajador", "periodo", "tipo")},
            },
        ),
    ]
