# Generated by Django 5.2.8 on 2025-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('tipo_usuario', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('usuario', 'Usuario')], db_comment='Rol del usuario en el sistema (ej: admin, usuario)', default='usuario', max_length=20)),
                ('rut_base', models.IntegerField(db_comment='RUT sin dígito verificador')),
                ('rut_dv', models.CharField(db_comment='Dígito verificador', max_length=1)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('email', models.EmailField(db_comment='Email de login', max_length=120, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(db_comment='Indica si el usuario puede iniciar sesión', default=True)),
                ('is_staff', models.BooleanField(db_comment='Indica si el usuario puede acceder al panel de admin', default=False)),
                ('creado_at', models.DateTimeField(auto_now_add=True, db_comment='Fecha de creación del registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'constraints': [models.UniqueConstraint(fields=('rut_base', 'rut_dv'), name='uk_usuario_rut')],
            },
        ),
    ]
