# Generated by Django 5.2.8 on 2025-11-07 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdminCondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_condominio', models.ForeignKey(db_column='id_condominio', on_delete=django.db.models.deletion.CASCADE, to='core.condominio')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin por Condominio',
                'verbose_name_plural': 'Admins por Condominio',
                'db_table': 'usuario_admin_condo',
                'unique_together': {('id_usuario', 'id_condominio')},
            },
        ),
    ]
