# Generated by Django 5.2.8 on 2025-11-11 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grupo_unidad'),
        ('usuarios', '0002_usuarioadmincondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copropietario',
            fields=[
                ('id_coprop', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(db_comment='Porcentaje de propiedad sobre la unidad (ej: 100.000 o 50.000)', decimal_places=3, max_digits=6)),
                ('desde', models.DateField(db_comment='Fecha inicio de propiedad')),
                ('hasta', models.DateField(blank=True, db_comment='Fecha fin de propiedad (si se vendió)', null=True)),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.RESTRICT, to='core.unidad', verbose_name='Unidad')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario')),
            ],
            options={
                'verbose_name': 'Copropietario',
                'verbose_name_plural': 'Copropietarios',
                'db_table': 'copropietario',
                'unique_together': {('id_unidad', 'id_usuario', 'desde')},
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id_residencia', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(choices=[('propietario', 'Propietario'), ('arrendatario', 'Arrendatario')], db_comment='Indica si el residente es el dueño o un arrendatario', max_length=20)),
                ('desde', models.DateField(db_comment='Fecha inicio de residencia')),
                ('hasta', models.DateField(blank=True, db_comment='Fecha fin de residencia', null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.unidad', verbose_name='Unidad')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Residente')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'db_table': 'residencia',
                'unique_together': {('id_unidad', 'id_usuario', 'desde')},
            },
        ),
    ]
